language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./install.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./install.sh python3; fi

script:
  - python godebian-server.py
  - cd godebian; python -m unittest test

branches:
  only:
    - master

sudo: true
