#!/bin/bash
set -e

# We're using the latest shiniest version of flask,
# so make it simple to update it.

rm -f flask.py
wget http://github.com/mitsuhiko/flask/raw/master/flask.py
git add flask.py
git commit -m 'Updating flask.py.' flask.py

